name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4   # updated

    - name: Set up Java JDK
      uses: actions/setup-java@v4  # updated
      with:
        distribution: temurin
        java-version: 17

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: StudyDiscussionClub-apk
        path: app/build/outputs/apk/debug/app-debug.apk
